filmy = [
	{
		"flag": "us",
		"title": "Magnolia",
		"originalTitle": "",
		"year": "1999",
		"url": "https://www.imdb.com/title/tt0175880",
		"imdbRating": "8",
		"directors": "Paul Thomas Anderson",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt0175880",
			"title": "Magnolia",
			"fullTitle": "Magnolia (1999)",
			"type": "Movie",
			"year": "1999",
			"videoId": "cxcegktcxSM",
			"videoUrl": "https://www.youtube.com/watch?v=cxcegktcxSM",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/magnolia/",
		"rymRating": "3.83",
		"rtUrl": "https://www.rottentomatoes.com/m/magnolia",
		"rtRating": "?"
	},
	{
		"flag": "fr",
		"title": "La Haine",
		"originalTitle": "La haine",
		"year": "1995",
		"url": "https://www.imdb.com/title/tt0113247",
		"imdbRating": "8.1",
		"directors": "Mathieu Kassovitz",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt0113247",
			"title": "La Haine",
			"fullTitle": "La Haine (1995)",
			"type": "Movie",
			"year": "1995",
			"videoId": "5Hs6GwQPAQE",
			"videoUrl": "https://www.youtube.com/watch?v=5Hs6GwQPAQE",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/la_haine/",
		"rymRating": "3.87",
		"rtUrl": "https://www.rottentomatoes.com/m/hate",
		"rtRating": "?"
	},
	{
		"flag": "de",
		"title": "Aguirre, the Wrath of God",
		"originalTitle": "Aguirre, der Zorn Gottes",
		"year": "1972",
		"url": "https://www.imdb.com/title/tt0068182",
		"imdbRating": "7.9",
		"directors": "Werner Herzog",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt0068182",
			"title": "Aguirre, the Wrath of God",
			"fullTitle": "Aguirre, the Wrath of God (1972)",
			"type": "Movie",
			"year": "1972",
			"videoId": "eJDuicFyJPg",
			"videoUrl": "https://www.youtube.com/watch?v=eJDuicFyJPg",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/aguirre__der_zorn_gottes/",
		"rymRating": "4.04",
		"rtUrl": "https://www.rottentomatoes.com/m/aguirre_the_wrath_of_god",
		"rtRating": "?"
	},
	{
		"flag": "jp",
		"title": "Seven Samurai",
		"originalTitle": "Shichinin no samurai",
		"year": "1954",
		"url": "https://www.imdb.com/title/tt0047478",
		"imdbRating": "8.6",
		"directors": "Akira Kurosawa",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt0047478",
			"title": "Seven Samurai",
			"fullTitle": "Seven Samurai (1954)",
			"type": "Movie",
			"year": "1954",
			"videoId": "8V4dEWPJKNk",
			"videoUrl": "https://www.youtube.com/watch?v=8V4dEWPJKNk",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/\u4e03\u4eba\u306e\u4f8d/",
		"rymRating": "4.30",
		"rtUrl": "https://www.rottentomatoes.com/m/seven_samurai_1956",
		"rtRating": "?"
	},
	{
		"flag": "fr",
		"title": "Of Gods and Men",
		"originalTitle": "Des hommes et des dieux",
		"year": "2010",
		"url": "https://www.imdb.com/title/tt1588337",
		"imdbRating": "7.2",
		"directors": "Xavier Beauvois",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt1588337",
			"title": "Of Gods and Men",
			"fullTitle": "Of Gods and Men (2010)",
			"type": "Movie",
			"year": "2010",
			"videoId": "nhQzn2gVGjQ",
			"videoUrl": "https://www.youtube.com/watch?v=nhQzn2gVGjQ",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/des_hommes_et_des_dieux/",
		"rymRating": "3.24",
		"rtUrl": "https://www.rottentomatoes.com/m/of-men-and-gods",
		"rtRating": "?"
	},
	{
		"flag": "wo",
		"title": "Into the Inferno",
		"originalTitle": "",
		"year": "2016",
		"url": "https://www.imdb.com/title/tt4846318",
		"imdbRating": "7.2",
		"directors": "Werner Herzog",
		"isDocu": true,
		"yttrailer": {
			"imDbId": "tt4846318",
			"title": "Into the Inferno",
			"fullTitle": "Into the Inferno (2016)",
			"type": "Movie",
			"year": "2016",
			"videoId": "YoSmPkWmG4k",
			"videoUrl": "https://www.youtube.com/watch?v=YoSmPkWmG4k",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/into_the_inferno/",
		"rymRating": "3.54",
		"rtUrl": "https://www.rottentomatoes.com/m/into_the_inferno",
		"rtRating": "?"
	},
	{
		"flag": "at",
		"title": "Amour",
		"originalTitle": "",
		"year": "2012",
		"url": "https://www.imdb.com/title/tt1602620",
		"imdbRating": "7.9",
		"directors": "Michael Haneke",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt1602620",
			"title": "Amour",
			"fullTitle": "Amour (2012)",
			"type": "Movie",
			"year": "2012",
			"videoId": "VMOugpyFf3A",
			"videoUrl": "https://www.youtube.com/watch?v=VMOugpyFf3A",
			"errorMessage": ""
		},
		"rymUrl": "?",
		"rymRating": "?",
		"rtUrl": "https://www.rottentomatoes.com/m/amour_2013",
		"rtRating": "?"
	},
	{
		"flag": "de",
		"title": "Stroszek",
		"originalTitle": "",
		"year": "1977",
		"url": "https://www.imdb.com/title/tt0075276",
		"imdbRating": "7.9",
		"directors": "Werner Herzog",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt0075276",
			"title": "Stroszek",
			"fullTitle": "Stroszek (1977)",
			"type": "Movie",
			"year": "1977",
			"videoId": "4fM4fL5KK5k",
			"videoUrl": "https://www.youtube.com/watch?v=4fM4fL5KK5k",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/stroszek/",
		"rymRating": "3.89",
		"rtUrl": "https://www.rottentomatoes.com/m/stroszek",
		"rtRating": "?"
	},
	{
		"flag": "gb",
		"title": "The Souvenir",
		"originalTitle": "",
		"year": "2019",
		"url": "https://www.imdb.com/title/tt6920356",
		"imdbRating": "6.4",
		"directors": "Joanna Hogg",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt6920356",
			"title": "The Souvenir",
			"fullTitle": "The Souvenir (2019)",
			"type": "Movie",
			"year": "2019",
			"videoId": "t9Al2nC0vzY",
			"videoUrl": "https://www.youtube.com/watch?v=t9Al2nC0vzY",
			"errorMessage": ""
		},
		"rymUrl": "?",
		"rymRating": "?",
		"rtUrl": "https://www.rottentomatoes.com/m/the_souvenir",
		"rtRating": "?"
	},
	{
		"flag": "tr",
		"title": "Butterflies",
		"originalTitle": "Kelebekler",
		"year": "2018",
		"url": "https://www.imdb.com/title/tt7318202",
		"imdbRating": "7.4",
		"directors": "Tolga Kara\u00e7elik",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt7318202",
			"title": "Butterflies",
			"fullTitle": "Butterflies (2018)",
			"type": "Movie",
			"year": "2018",
			"videoId": "5haJDNWiqUY",
			"videoUrl": "https://www.youtube.com/watch?v=5haJDNWiqUY",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/kelebekler/",
		"rymRating": "3.24",
		"rtUrl": "https://www.rottentomatoes.com/m/butterflies_2018",
		"rtRating": "?"
	},
	{
		"flag": "fr",
		"title": "Cleo from 5 to 7",
		"originalTitle": "Cl\u00e9o de 5 \u00e0 7",
		"year": "1962",
		"url": "https://www.imdb.com/title/tt0055852",
		"imdbRating": "7.9",
		"directors": "Agn\u00e8s Varda",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt0055852",
			"title": "Cleo from 5 to 7",
			"fullTitle": "Cleo from 5 to 7 (1962)",
			"type": "Movie",
			"year": "1962",
			"videoId": "6L9JBr5jKvg",
			"videoUrl": "https://www.youtube.com/watch?v=6L9JBr5jKvg",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/cleo_de_5_a_7/",
		"rymRating": "3.84",
		"rtUrl": "https://www.rottentomatoes.com/m/cleo_de_5_a_7",
		"rtRating": "?"
	},
	{
		"flag": "wo",
		"title": "The Act of Killing",
		"originalTitle": "",
		"year": "2012",
		"url": "https://www.imdb.com/title/tt2375605",
		"imdbRating": "8.2",
		"directors": "Joshua Oppenheimer, Anonymous, Christine Cynn",
		"isDocu": true,
		"yttrailer": {
			"imDbId": "tt2375605",
			"title": "The Act of Killing",
			"fullTitle": "The Act of Killing (2012)",
			"type": "Movie",
			"year": "2012",
			"videoId": "SD5oMxbMcHM",
			"videoUrl": "https://www.youtube.com/watch?v=SD5oMxbMcHM",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/the_act_of_killing/",
		"rymRating": "4.03",
		"rtUrl": "https://www.rottentomatoes.com/m/the_act_of_killing",
		"rtRating": "?"
	},
	{
		"flag": "ir",
		"title": "There Is No Evil",
		"originalTitle": "Sheytan vojud nadarad",
		"year": "2020",
		"url": "https://www.imdb.com/title/tt11697844",
		"imdbRating": "7.4",
		"directors": "Mohammad Rasoulof",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt11697844",
			"title": "There Is No Evil",
			"fullTitle": "There Is No Evil (2020)",
			"type": "Movie",
			"year": "2020",
			"videoId": "tu-WUq_emxU",
			"videoUrl": "https://www.youtube.com/watch?v=tu-WUq_emxU",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/\u0634\u06cc\u0637\u0627\u0646_\u0648\u062c\u0648\u062f_\u0646\u062f\u0627\u0631\u062f/",
		"rymRating": "3.21",
		"rtUrl": "https://www.rottentomatoes.com/m/there_is_no_evil",
		"rtRating": "?"
	},
	{
		"flag": 'wo',
		"title": "The Young Karl Marx",
		"originalTitle": "Le jeune Karl Marx",
		"year": "2017",
		"url": "https://www.imdb.com/title/tt1699518",
		"imdbRating": "6.6",
		"directors": "Raoul Peck",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt1699518",
			"title": "The Young Karl Marx",
			"fullTitle": "The Young Karl Marx (2017)",
			"type": "Movie",
			"year": "2017",
			"videoId": "qssSV56-wO8",
			"videoUrl": "https://www.youtube.com/watch?v=qssSV56-wO8",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/le_jeune_karl_marx/",
		"rymRating": "3.02",
		"rtUrl": "https://www.rottentomatoes.com/m/the_young_karl_marx",
		"rtRating": "?"
	},
	{
		"flag": "fr",
		"title": "Welcome to the Sticks",
		"originalTitle": "Bienvenue chez les Ch'tis",
		"year": "2008",
		"url": "https://www.imdb.com/title/tt1064932",
		"imdbRating": "7.1",
		"directors": "Dany Boon",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt1064932",
			"title": "Welcome to the Sticks",
			"fullTitle": "Welcome to the Sticks (2008)",
			"type": "Movie",
			"year": "2008",
			"videoId": "_6Mx3HZ4_tI",
			"videoUrl": "https://www.youtube.com/watch?v=_6Mx3HZ4_tI",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/bienvenue_chez_les_chtis/",
		"rymRating": "2.57",
		"rtUrl": "https://www.rottentomatoes.com/m/bienvenue-chez-les-chtis-welcome-to-the-land-of-shtis-welcome-to-the-sticks",
		"rtRating": "?"
	},
	{
		"flag": "us",
		"title": "Synecdoche, New York",
		"originalTitle": "",
		"year": "2008",
		"url": "https://www.imdb.com/title/tt0383028",
		"imdbRating": "7.6",
		"directors": "Charlie Kaufman",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt0383028",
			"title": "Synecdoche, New York",
			"fullTitle": "Synecdoche, New York (2008)",
			"type": "Movie",
			"year": "2008",
			"videoId": "XIizh6nYnTU",
			"videoUrl": "https://www.youtube.com/watch?v=XIizh6nYnTU",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/synecdoche__new_york/",
		"rymRating": "3.85",
		"rtUrl": "https://www.rottentomatoes.com/m/synecdoche_new_york",
		"rtRating": "?"
	},
	{
		"flag": "cn",
		"title": "Yellow Earth",
		"originalTitle": "Huang tu di",
		"year": "1984",
		"url": "https://www.imdb.com/title/tt0087433",
		"imdbRating": "7.1",
		"directors": "Kaige Chen",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt0087433",
			"title": "Yellow Earth",
			"fullTitle": "Yellow Earth (1984)",
			"type": "Movie",
			"year": "1984",
			"videoId": "",
			"videoUrl": "",
			"errorMessage": "Trailer not founded"
		},
		"rymUrl": "https://rateyourmusic.com/film/\u9ec4\u571f\u5730/",
		"rymRating": "3.47",
		"rtUrl": "https://www.rottentomatoes.com/m/Yellow_Earth",
		"rtRating": "?"
	},
	{
		"flag": "pl",
		"title": "The Last Family",
		"originalTitle": "Ostatnia rodzina",
		"year": "2016",
		"url": "https://www.imdb.com/title/tt5936692",
		"imdbRating": "7.6",
		"directors": "Jan P. Matuszynski",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt5936692",
			"title": "The Last Family",
			"fullTitle": "The Last Family (2016)",
			"type": "Movie",
			"year": "2016",
			"videoId": "XfFt9RfO9Bc",
			"videoUrl": "https://www.youtube.com/watch?v=XfFt9RfO9Bc",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/ostatnia_rodzina/",
		"rymRating": "3.63",
		"rtUrl": "https://www.rottentomatoes.com/m/ostatnia_rodzina",
		"rtRating": "?"
	},
	{
		"flag": "se",
		"title": "A Pigeon Sat on a Branch Reflecting on Existence",
		"originalTitle": "En duva satt p\u00e5 en gren och funderade p\u00e5 tillvaron",
		"year": "2014",
		"url": "https://www.imdb.com/title/tt1883180",
		"imdbRating": "7.0",
		"directors": "Roy Andersson",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt1883180",
			"title": "A Pigeon Sat on a Branch Reflecting on Existence",
			"fullTitle": "A Pigeon Sat on a Branch Reflecting on Existence (2014)",
			"type": "Movie",
			"year": "2014",
			"videoId": "JGwGyo5Ywpo",
			"videoUrl": "https://www.youtube.com/watch?v=JGwGyo5Ywpo",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/en_duva_satt_pa_en_gren_och_funderade_pa_tillvaron/",
		"rymRating": "3.36",
		"rtUrl": "https://www.rottentomatoes.com/m/en_duva_satt_pa_en_gren_och_funderade_pa_tillvaron",
		"rtRating": "?"
	},
	{
		"flag": "at",
		"title": "The White Ribbon",
		"originalTitle": "Das wei\u00dfe Band - Eine deutsche Kindergeschichte",
		"year": "2009",
		"url": "https://www.imdb.com/title/tt1149362",
		"imdbRating": "7.8",
		"directors": "Michael Haneke",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt1149362",
			"title": "The White Ribbon",
			"fullTitle": "The White Ribbon (2009)",
			"type": "Movie",
			"year": "2009",
			"videoId": "9JOXs8KEiDY",
			"videoUrl": "https://www.youtube.com/watch?v=9JOXs8KEiDY",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/das_weisse_band/",
		"rymRating": "3.79",
		"rtUrl": "https://www.rottentomatoes.com/m/white_ribbon",
		"rtRating": "?"
	},
	{
		"flag": "fr",
		"title": "Faces Places",
		"originalTitle": "Visages villages",
		"year": "2017",
		"url": "https://www.imdb.com/title/tt5598102",
		"imdbRating": "7.9",
		"directors": "JR, Agn\u00e8s Varda",
		"isDocu": true,
		"yttrailer": {
			"imDbId": "tt5598102",
			"title": "Faces Places",
			"fullTitle": "Faces Places (2017)",
			"type": "Movie",
			"year": "2017",
			"videoId": "P7rFMO7ODBk",
			"videoUrl": "https://www.youtube.com/watch?v=P7rFMO7ODBk",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/visages__villages/",
		"rymRating": "3.54",
		"rtUrl": "https://www.rottentomatoes.com/m/visages_villages",
		"rtRating": "?"
	},
	{
		"flag": "us",
		"title": "Manhattan",
		"originalTitle": "",
		"year": "1979",
		"url": "https://www.imdb.com/title/tt0079522",
		"imdbRating": "7.9",
		"directors": "Woody Allen",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt0079522",
			"title": "Manhattan",
			"fullTitle": "Manhattan (1979)",
			"type": "Movie",
			"year": "1979",
			"videoId": "BNiIMhC8oII",
			"videoUrl": "https://www.youtube.com/watch?v=BNiIMhC8oII",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/manhattan/",
		"rymRating": "3.83",
		"rtUrl": "https://www.rottentomatoes.com/m/manhattan",
		"rtRating": "?"
	},
	{
		"flag": "us",
		"title": "Under the Silver Lake",
		"originalTitle": "",
		"year": "2018",
		"url": "https://www.imdb.com/title/tt5691670",
		"imdbRating": "6.5",
		"directors": "David Robert Mitchell",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt5691670",
			"title": "Under the Silver Lake",
			"fullTitle": "Under the Silver Lake (2018)",
			"type": "Movie",
			"year": "2018",
			"videoId": "mwgUesU1pz4",
			"videoUrl": "https://www.youtube.com/watch?v=mwgUesU1pz4",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/under_the_silver_lake/",
		"rymRating": "3.37",
		"rtUrl": "https://www.rottentomatoes.com/m/under_the_silver_lake",
		"rtRating": "?"
	},
	{
		"flag": "us",
		"title": "Snowden",
		"originalTitle": "",
		"year": "2016",
		"url": "https://www.imdb.com/title/tt3774114",
		"imdbRating": "7.3",
		"directors": "Oliver Stone",
		"isDocu": false,
		"yttrailer": {
			"imDbId": "tt3774114",
			"title": "Snowden",
			"fullTitle": "Snowden (2016)",
			"type": "Movie",
			"year": "2016",
			"videoId": "QlSAiI3xMh4",
			"videoUrl": "https://www.youtube.com/watch?v=QlSAiI3xMh4",
			"errorMessage": ""
		},
		"rymUrl": "https://rateyourmusic.com/film/snowden/",
		"rymRating": "2.96",
		"rtUrl": "https://www.rottentomatoes.com/m/snowden",
		"rtRating": "?"
	}
]